### ISSUE TITLE
Move `--frozen` flag check to a separate pre-localization step

### ISSUE THREAD

**Issue by maxprilutskiy** [replexica/replexica#110]
**Description**  
Move the `--frozen` flag check to a separate step before starting the translation loop. This ensures the process fails fast if necessary, saving API calls and improving the developer experience.

**Proposed Solution**  
Refactor the translation process to move the `--frozen` flag checks before entering the main translation loop.

**References**
https://github.com/replexica/replexica/blob/main/packages/cli/src/i18n.ts

**Comment by partik03** [comment]
@maxprilutskiy can you provide some more context to this issue as I think now we are not checking the frozen flag at all

**Comment by maxprilutskiy** [comment]
Hey @partik03 - nice catch! Indeed, looks like we lost `--frozen` at some point during refactoring this week.

Here's the idea behind the flag, briefly:

When `--frozen` is enabled and we detect that the lockfile would be updated after running `replexica i18n`, we should exit early with a non-zero code and error message, before even starting the localization loop. This helps quickly check for potential changes to localization files, without actually starting localization, which can be useful in CI/CD.

Originally, we had the `--frozen` check inside the localization loop. That wasn't ideal since it would start processing localizations only to exit partway through, wasting API calls and processing time.

So, we need to add the `--frozen` check somewhere here https://github.com/replexica/replexica/blob/main/packages/cli/src/cli/i18n.ts#L92, before the localization loop begins. If we detect that source entry hashes would need updating in the lockfile, we exit immediately without starting localization.

**Comment by partik03** [comment]
@maxprilutskiy got it, will add the flag again then

**Comment by partik03** [comment]
@maxprilutskiy raised the PR for this one
