### ISSUE TITLE
Update GitHub issue templates

### ISSUE THREAD

**Issue by maxprilutskiy** [replexica/replexica#112]
### What
Update the GitHub issue templates to use the new workflow described in GitHub's documentation, and remove the current `ISSUE_TEMPLATE.md`. Create two types of templates:
1. **Bug Report**: Should ask for CLI version, OS, and other relevant details.
2. **Feature/Improvement**: Should follow the streamlined template.

### Why
Improves the developer experience and makes it easier for users who are short on time to report issues.

### How
1. Read the GitHub documentation on configuring issue templates.
2. Create two new templates, one for bugs and one for features/improvements.
3. For the bug report template:
   - Include fields for CLI version and OS.
   - Include sections for description, steps to reproduce, expected vs actual behavior, and additional context.
4. For the feature/improvement template:
   - Include sections for WHAT, WHY, and HOW.

**Comment by Allan2000-Git** [comment]
@maxprilutskiy I'd love to work on this issue.

**Comment by Absterrg0** [comment]
@maxprilutskiy This issue has been addressed by PR #224, please check the changes made
