### ISSUE TITLE
Preserve JSON order

### ISSUE THREAD

**Issue by quentin-decre** [replexica/replexica#150]
### What

When we add translation keys to the source JSON file, it is translated to the target JSON file, but added at the end of the object, not at the same positions.
![image](https://github.com/user-attachments/assets/d9bba211-fbdf-4d86-84de-203cddaa816e)

### Why

We want to be able to do translations check side to side, and this makes it difficult.

### How

Either keep the same order when adding new keys, or going through source and target files to re-order the keys in the same order.

**Comment by quentin-decre** [comment]
I used that to go through translations files after new translations are added : https://www.npmjs.com/package/prettier-plugin-sort-json

**Comment by maxprilutskiy** [comment]
Nice! Adding to the roadmap 👌

**Comment by maxprilutskiy** [comment]
Will be released in a couple of minutes as part of `v0.36.2`! 🎉
