### ISSUE TITLE
Exclude files from a bucket

### ISSUE THREAD

**Issue by quentin-decre** [replexica/replexica#151]
### What

This is a feature request.
We would like to be able to exclude some paths / documents from a bucket.

### Why

We will use replexica to translate blog posts from one language to another. We want 95% of the blog-posts to be available in both languages. But for 5%, this makes no sense. One blog post can be very specific for one country for example.

### How

Here is how graphql-codgen which also has a bucket concept handle it :
![image](https://github.com/user-attachments/assets/6dbbdcc9-88b0-401e-8463-f56511492e5d)

Have you noticed the "!" in front of the paths to exclude ?

**Comment by maxprilutskiy** [comment]
Gotcha Quentin, makes total sense. Taking a look at how it works in `graphql-codgen`, and will report back.

Should be relatively straightforward thing to implement.

**Comment by maxprilutskiy** [comment]
Should be available in `v0.37.0`! 

Replexica CLI should upgrade the structure of the `i18n.json` file automatically, for the details on the new format – see #158.
