### ISSUE TITLE
Action must do nothing when commit message contains '[skip i18n]'

### ISSUE THREAD

**Issue by maxprilutskiy** [replexica/replexica#192]
### What
Add a feature to our custom GitHub Action that skips i18n processing when the commit message contains '[skip i18n]'.

### Why
This allows developers to bypass i18n checks, if that's needed for debugging GitHub workflows.

### How
1. Parse the current commit message in the action
2. Check for '[skip i18n]' string (case-insensitive)
3. If found, exit the action early without processing, and print a message
4. If not found, continue with normal i18n checks

We could use a regex pattern to match the string, accounting for possible variations in spacing or capitalization.

**Comment by Dhruvnotfound** [comment]
hey would love to work on this!

**Comment by maxprilutskiy** [comment]
reopened, more details here: https://github.com/replexica/replexica/pull/249#issuecomment-2425187681

**Comment by partik03** [comment]
@maxprilutskiy This issue should be closed as already done
