### ISSUE TITLE
Fix CLI overwriting i18n.json when unsupported locale is added

### ISSUE THREAD

**Issue by maxprilutskiy** [replexica/replexica#198]
### What
The CLI overwrites i18n.json with a default template when an unsupported locale is added. It should throw an error instead.

### Why
Overwriting the file can lead to data loss and confusion. Users should be alerted to their mistake immediately.

### How
1. Modify the CLI to check for unsupported locales before processing i18n.json.
2. If an unsupported locale is found, throw a clear error message.
3. Ensure the original i18n.json remains untouched.
4. Update documentation to clarify supported locales and error handling.

**Comment by dankgarlic1** [comment]
/attempt
I am unable to authenticate via cli
