### ISSUE TITLE
Add support for Next.js *pages* router

### ISSUE THREAD

**Issue by maxprilutskiy** [replexica/replexica#25]
## Description
Let's level up our support for Next.js by adding compatibility with the *pages* router.

## Motivation
Not everyone's on board with the "App router" yet. By adding support for the *pages* router, we can cater to users who prefer this setup.

**Comment by maxprilutskiy** [comment]
cc @mathio for visibility

**Comment by Cliftonz** [comment]
Upvoting this!

**Comment by maxprilutskiy** [comment]
This is now WIP.

**Comment by sarcasvik** [comment]
Hi, @maxprilutskiy 

Can I contribute to this issue?

**Comment by maxprilutskiy** [comment]
Replexica will continue supporting nextjs, both pages and app router, along with supporting every existing i18n library for react. Closing the issue for now.
