### ISSUE TITLE
Add support for XML file format

### ISSUE THREAD

**Issue by vrcprl** [replexica/replexica#288]
### What
Implement a loader for XML files in Replexica.

### Why
To support developers and enterprise systems using XML for cross-platform applications.

### How
1. Create a new loader in `packages/cli/src/loaders/xml.ts`
2. Implement parsing logic for XML structure
3. Add two unit tests in `packages/cli/src/loaders/index.spec.ts`:
   - Test parsing a simple XML file
   - Test handling plurals in XML entries
4. Update `@replexica/spec` to include XML format
5. Generate a changeset using `pnpm new` for both 'replexica' and '@replexica/cli' packages
6. In the pull request, include a link to the XML specification used.

### After completing the task
Noticed a file format Replexica doesn't yet support? Please create a new GitHub ticket (if it doesn't yet exist!), using the format/structure of this GitHub issue.

**Comment by partik03** [comment]
@maxprilutskiy raised PR for this one

**Comment by partik03** [comment]
@maxprilutskiy we can close this one

**Comment by maxprilutskiy** [comment]
Resolved in #298
