### ISSUE TITLE
Add support for XLIFF (.xlf) file format

### ISSUE THREAD

**Issue by vrcprl** [replexica/replexica#291]
### What
Implement a loader for XLIFF files in Replexica.

### Why
To support developers, LSPs, and translation agencies working on software, web, and mobile app localization.

### How
1. Create a new loader in `packages/cli/src/loaders/xliff.ts`
2. Implement parsing logic for XLIFF XML structure
3. Add two unit tests in `packages/cli/src/loaders/index.spec.ts`:
   - Test parsing a simple XLIFF file
   - Test handling context groups in XLIFF entries
4. Update `@replexica/spec` to include XLIFF format
5. Generate a changeset using `pnpm new` for both 'replexica' and '@replexica/cli' packages
6. In the pull request, include a link to the XLIFF specification used.

### After completing the task
Noticed a file format Replexica doesn't yet support? Please create a new GitHub ticket (if it doesn't yet exist!), using the format/structure of this GitHub issue.

**Comment by partik03** [comment]
@maxprilutskiy was working on this using a library [xliff](https://www.npmjs.com/package/xliff) but this file does not contain type definition file for the function, hence we need to create modules for type definitions for the functions used
So should I proceed with this approach or you suggest doing something else

**Comment by maxprilutskiy** [comment]
assigning to @Nithishvb

**Comment by maxprilutskiy** [comment]
this one is up for grabs again!

**Comment by partik03** [comment]
@maxprilutskiy raised a fresh PR for this one
