### ISSUE TITLE
Add support for SRT (SubRip Subtitle) file format

### ISSUE THREAD

**Issue by vrcprl** [replexica/replexica#293]
### What
Implement a loader for SRT files in Replexica.

### Why
To support video editors and translators working with video subtitles.

### How
1. Create a new loader in `packages/cli/src/loaders/srt.ts`
2. Implement parsing logic for SRT structure
3. Add two unit tests in `packages/cli/src/loaders/index.spec.ts`:
   - Test parsing a simple SRT file
   - Test handling multi-line subtitles in SRT entries
4. Update `@replexica/spec` to include SRT format
5. Generate a changeset using `pnpm new` for both 'replexica' and '@replexica/cli' packages
6. In the pull request, include a link to the SRT specification used.

### After completing the task
Noticed a file format Replexica doesn't yet support? Please create a new GitHub ticket (if it doesn't yet exist!), using the format/structure of this GitHub issue.

**Comment by partik03** [comment]
@maxprilutskiy please assign this issue to me I am already trying to solve this

**Comment by maxprilutskiy** [comment]
@partik03 assigned, go for it!
