### ISSUE TITLE
[Language request] Add support for Catalan

### ISSUE THREAD

**Issue by picsoung** [replexica/replexica#63]
## Description
I would love to be able to support a new language: Catalan

## Motivation
I am based in Barcelona, and most websites have three languages: English, Spanish, Catalan

## Proposed Solution
```
const replexicaConfig = {
  locale: {
    source: 'en',
    targets: ['es', 'ca'],
  },
};
```

**Comment by maxprilutskiy** [comment]
Loving it!

We're releasing a bunch of languages next week. Stay tuned ;)
